### ISSUE TITLE
transport.username is not respected

### ISSUE THREAD

**Issue by alexpop** [test-kitchen/kitchen-ec2#225]
With code in master(c97798142d639ff3cff435b5516eb3be00bce6a3), I'm using this kitchen.ec2.yml config to converge `us-west-1` instances:

```
platforms:
  - name: centos-6
    driver:
      image_id: ami-e73ccda3
    transport:
      username: root
    provisioner:
      sudo: false
```

Kitchen is attempting to login with the default username(`centos`) instead of the configured one(`root`):

```
$ bundle exec kitchen converge
-----> Starting Kitchen (v1.5.0)
-----> Creating <default-centos-6>...
       Detected platform: centos version 5 on x86_64. Instance Type: m3.medium. Default username: centos (default).
...SNIP...
       Waited 25/300s for instance <i-3c16fb89> to become ready.
       EC2 instance <i-3c16fb89> ready.
       Waiting for SSH service on ec2-54-183-129-223.us-west-1.compute.amazonaws.com:22, retrying in 3 seconds
       Waiting for SSH service on ec2-54-183-129-223.us-west-1.compute.amazonaws.com:22, retrying in 3 seconds
       Waiting for SSH service on ec2-54-183-129-223.us-west-1.compute.amazonaws.com:22, retrying in 3 seconds
...
```

After I cancel the `Waiting for SSH` loop, the contents of `.kitchen/default-centos-6.yml` is:

```

---
username: centos
server_id: i-3c16fb89
hostname: ec2-54-183-129-223.us-west-1.compute.amazonaws.com
```

I'm able to converge fine with the same config if I use the kitchen-ec2 master ref 0e363e068c8d03978358b31b19b1f9dc09fac25d

**Comment by jkeiser** [comment]
Can you add `-l debug` so we can find out what it's actually using to connect? The default username isn't necessarily what it will use to connect. We really need to get test-kitchen to give more information about how it's connecting.

**Comment by jkeiser** [comment]
In my tests, furthermore, it is in fact using `transport.username` to connect:

```
driver:
  name: ec2
  aws_ssh_key_id: jkeiser
  region: us-west-2

transport:
  ssh_key: ~/.ssh/jkeiser

# This is a big list of automatically supported platforms
platforms:
  - name: centos-6.5
    transport:
      username: blah
```

(Well, in this case it's failing to connect, but when I run with `debug` on it's clearly using `blah`.)

**Comment by proffalken** [comment]
+1 for further information including debug logs, I'm struggling to see how
a version bump and rubocop settings can cause the issue outlined above?

**Comment by jkeiser** [comment]
A version bump could cause the issue because I've changed around how username works (changed a lot of things) in master; but I suspect it's not the issue in this case (just a misleading message there).

**Comment by alexpop** [comment]
Thanks for looking into this issue. Here's the debug output:
```
$ bundle exec kitchen converge -l debug
-----> Starting Kitchen (v1.5.0)
D      Berksfile found at /Users/apop/git/cc/core/test/kitchen-omnibus-cc/Berksfile, loading Berkshelf
D      Berkshelf 4.1.1 library loaded
-----> Creating <default-centos-6>...
D      Image for default-centos-6: Amazon_CentOS_6-5-x86-64_1.0rev15_2015-Jun-29_12.39.00.  Architecture: x86_64, Virtualization: hvm, Storage: ebs standard, Created: 2015-06-30T09:43:50.000Z
       Detected platform: centos version 5 on x86_64. Instance Type: m3.medium. Default username: centos (default).
D      No SSH username specified: using default username centos  for image ami-e73ccda3, which we detected as centos 5 x86_64.
       If you are not using an account that qualifies under the AWS
free-tier, you may be charged to run these suites. The charge
should be minimal, but neither Test Kitchen nor its maintainers
are responsible for your incurred costs.

D      Creating EC2 instance in region us-west-1 with properties:
D      - instance_type = "m3.medium"
D      - ebs_optimized = false
D      - image_id = "ami-e73ccda3"
D      - key_name = "kitchen-key-compliance"
D      - subnet_id = nil
D      - private_ip_address = nil
D      - network_interfaces = [{:device_index=>0, :associate_public_ip_address=>true, :delete_on_termination=>true, :groups=>["sg-abe2eace"]}]
       Instance <i-718f63c4> requested.
       Polling AWS for existence, attempt 0...
       Attempting to tag the instance, 0 retries
       EC2 instance <i-718f63c4> created.
       Waited 0/300s for instance <i-718f63c4> to become ready.
       Waited 5/300s for instance <i-718f63c4> to become ready.
       Waited 10/300s for instance <i-718f63c4> to become ready.
       Waited 15/300s for instance <i-718f63c4> to become ready.
       Waited 20/300s for instance <i-718f63c4> to become ready.
       EC2 instance <i-718f63c4> ready.
D      [SSH] opening connection to centos@ec2-54-183-138-29.us-west-1.compute.amazonaws.com<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :port=>22, :compression=>true, :compression_level=>6, :keepalive=>true, :keepalive_interval=>60, :timeout=>15, :keys_only=>true, :keys=>["/Users/apop/git/cc/core/test/kitchen-omnibus-cc/ssh/kitchen-key-compliance.pem"], :auth_methods=>["publickey"]}>
D      [SSH] connection failed (#<Net::SSH::ConnectionTimeout: Net::SSH::ConnectionTimeout>)
       Waiting for SSH service on ec2-54-183-138-29.us-west-1.compute.amazonaws.com:22, retrying in 3 seconds
D      [SSH] opening connection to centos@ec2-54-183-138-29.us-west-1.compute.amazonaws.com<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :port=>22, :compression=>true, :compression_level=>6, :keepalive=>true, :keepalive_interval=>60, :timeout=>15, :keys_only=>true, :keys=>["/Users/apop/git/cc/core/test/kitchen-omnibus-cc/ssh/kitchen-key-compliance.pem"], :auth_methods=>["publickey"], :user=>"centos"}>
```

for the attached [.kitchen.yml](https://github.com/test-kitchen/kitchen-ec2/files/131398/default.kitchen.yml.txt)

And here's the output when username `blah` is used:
```
      Waited 15/300s for instance <i-5c8f63e9> to become ready.
       Waited 20/300s for instance <i-5c8f63e9> to become ready.
       EC2 instance <i-5c8f63e9> ready.
D      [SSH] opening connection to blah@ec2-54-153-79-206.us-west-1.compute.amazonaws.com<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :port=>22, :compression=>true, :compression_level=>6, :keepalive=>true, :keepalive_interval=>60, :timeout=>15, :keys_only=>true, :keys=>["/Users/apop/git/cc/core/test/kitchen-omnibus-cc/ssh/kitchen-key-compliance.pem"], :auth_methods=>["publickey"]}>
```

**Comment by jkeiser** [comment]
@alexpop ohhh. OK. This is a broken window. Let's see what we can do about it.

**Comment by jkeiser** [comment]
The issue only happens if username == 'root', because that is the default for ssh. I think we can fix this.

**Comment by jkeiser** [comment]
@alexpop: I believe you are hitting an instance of a larger bug: the fact that we now recognize `centos-6` as a "special" username means we will trigger that bug where we did not before. We're going to need to modify `test-kitchen` core to actually fix this.

**Comment by jkeiser** [comment]
Here's what's happening. When you type this:

```yaml
platforms:
  - name: ubuntu-14.04
```

We want to set the username to `ubuntu` since that's the default for official Ubuntu images. However, if you say this:

```yaml
platforms:
  - name: ubuntu-14.04
    transport:
      username: superduper
```

We need to honor that username. To do that, we only set the username to `ubuntu` if you didn't say a username yourself.  This is where the problem comes in: we check whether `transport.username == <default transport username>` (where default transport username is `"root"`). So if you write this:

```yaml
platforms:
  - name: ubuntu-14.04
    transport:
      username: root
```

Then we screw up! We set the username to `ubuntu`. Why? Because we think the user didn't actually type anything--after all, the username is set to the default!

The correct fix here is to add a method such as `is_set?(attr)` or `is_defaulted?(attr)` in `https://github.com/test-kitchen/test-kitchen/blob/master/lib/kitchen/configurable.rb`, which returns `true` if the user actually set the attribute, and `false` otherwise. Given the current implementation via `LazyHash`, this may be best implemented by storing the `config` that is [passed in to init_config](https://github.com/test-kitchen/test-kitchen/blob/master/lib/kitchen/configurable.rb#L193) as `@initial_config` or something. Then it could look like this:

```
def is_set?(attr)
  @initial_config.key?(attr)
end
```

Then the above kitchen-ec2 code could check `transport.is_set?(:username)` instead of checking whether the value equaled the default value.

**Comment by jkeiser** [comment]
@alexpop fyi, I believe the workaround for you is to change the platform name to `centos6` or `mycentos-6` or something we won't recognize as Centos 6. We're working on fixing on our side but not sure if this week.

**Comment by alexpop** [comment]
Great, thanks @jkeiser

**Comment by chrisgit** [comment]
@jkeiser Hi, we are also experiencing the same issue but the suggested work around does not appear to work for us.

We have changed the platform name (as below). Are we missing something?

`platforms:
- name: my-test
  driver_config:
    image_id: ami-XXX
    instance_type: "c3.large"
  transport:
    name: ssh
    username: root
    ssh_key: our_ssh_key
`

**Comment by chrisgit** [comment]
Have just read the code, I see what you mean

```
      def update_username(state)
        # TODO: if the user explicitly specified the transport's default username,
        # do NOT overwrite it!
        if instance.transport[:username] == instance.transport.class.defaults[:username]
          debug("No SSH username specified: using default username #{actual_platform.username} " \
                " for image #{config[:image_id]}, which we detected as #{actual_platform}.")
          state[:username] = actual_platform.username
        end
      end

...

          def username
            # Centos 6.x images use root as the username (but the "centos 6"
            # updateable image uses "centos")
            return "root" if version && version.start_with?("6.")
            "centos"
          end
```

We didn't specify the version, will try again tomorrow specifying a version.

**Comment by alexpop** [comment]
The platform name change didn't work for me either. I can't go back to `0.10.0` due to the optional `sudo` fix that was released in `1.0.0`.
Workaround for me was to find another centos image that worked with user `centos`.

**Comment by gretel** [comment]
we use custom `AMI`s that just require to login as `root`. therefore, this issue bothers us a lot. regards

**Comment by TemporarilyOffline** [comment]
FYI:  This also happens with windows platforms:

```
-----> Starting Kitchen (v1.6.0)
-----> Destroying <default-windows-2012r2>...
       Finished destroying <default-windows-2012r2> (0m0.00s).
-----> Kitchen is finished. (0m1.13s)
-----> Starting Kitchen (v1.6.0)
-----> Creating <default-windows-2012r2>...
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #create action: [undefined method `username' for nil:NilClass]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

Switching the `platforms:name:` from `windows-2012r2` to `mywindows-2012r2` switches the transport from winrm to ssh which also doesn't work.

I've back-dated kitchen-ec2 from 1.0.0 to 0.10.0 to bypass this.

**Comment by gsaslis** [comment]
Yep - not sure if this was ever resolved, but I also had what sounded like a similar problem, so I ended up downgrading back down to 0.10.0 to bypass the issue. 

Tried the configs suggested here, they didn't work for me... :(

**Comment by cheeseplus** [comment]
Should be resolved by above PR.

**Comment by thomasriley** [comment]
Using test-kitchen 1.17.0 & kitchen-ec2 1.3.2 and still seeing this same issue, setting transport.username is ignored no matter the platform name.
